//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRoom.Shared.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceLibrary
    {
        public string IssNo { get; set; }
        public string RefType { get; set; }
        public string RefCd { get; set; }
        public string RefNo { get; set; }
        public string RefInd { get; set; }
        public string RefId { get; set; }
        public string MapInd { get; set; }
        public string Descp { get; set; }
    }
}
