//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccountLeftMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountLeftMenu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AccountLeftMenu", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Summary.
        /// </summary>
        internal static string AcctSummary {
            get {
                return ResourceManager.GetString("AcctSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application / Customer Info.
        /// </summary>
        internal static string AppCusInfo {
            get {
                return ResourceManager.GetString("AppCusInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billed Transactions.
        /// </summary>
        internal static string BilledTransactions {
            get {
                return ResourceManager.GetString("BilledTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Profile.
        /// </summary>
        internal static string CorpCorporateProfile {
            get {
                return ResourceManager.GetString("CorpCorporateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card List.
        /// </summary>
        internal static string CrdCardList {
            get {
                return ResourceManager.GetString("CrdCardList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center.
        /// </summary>
        internal static string CstCostCentre {
            get {
                return ResourceManager.GetString("CstCostCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Info.
        /// </summary>
        internal static string CusAccCusInfo {
            get {
                return ResourceManager.GetString("CusAccCusInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string CusAddress {
            get {
                return ResourceManager.GetString("CusAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string CusContact {
            get {
                return ResourceManager.GetString("CusContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Details.
        /// </summary>
        internal static string CusCustomerDetails {
            get {
                return ResourceManager.GetString("CusCustomerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Profile.
        /// </summary>
        internal static string CusCustomerProfile {
            get {
                return ResourceManager.GetString("CusCustomerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Portal.
        /// </summary>
        internal static string CuspCustomerPortal {
            get {
                return ResourceManager.GetString("CuspCustomerPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event &amp; Notification.
        /// </summary>
        internal static string EvtEventNotify {
            get {
                return ResourceManager.GetString("EvtEventNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Details.
        /// </summary>
        internal static string FinFinancialDetails {
            get {
                return ResourceManager.GetString("FinFinancialDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Manager.
        /// </summary>
        internal static string FmgrFileManager {
            get {
                return ResourceManager.GetString("FmgrFileManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Transactions.
        /// </summary>
        internal static string OnlineTransactions {
            get {
                return ResourceManager.GetString("OnlineTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing Details.
        /// </summary>
        internal static string PrdPricingDetails {
            get {
                return ResourceManager.GetString("PrdPricingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        internal static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbilled Transactions.
        /// </summary>
        internal static string UnbilledTransactions {
            get {
                return ResourceManager.GetString("UnbilledTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage Control.
        /// </summary>
        internal static string UsUsageControl {
            get {
                return ResourceManager.GetString("UsUsageControl", resourceCulture);
            }
        }
    }
}
