//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CardtrendApplication {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CardtrendApplication() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CardtrendApplication", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string AdminLbl {
            get {
                return ResourceManager.GetString("AdminLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        internal static string ApplicationLbl {
            get {
                return ResourceManager.GetString("ApplicationLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application ID.
        /// </summary>
        internal static string ApplIdLbl {
            get {
                return ResourceManager.GetString("ApplIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized Signatory.
        /// </summary>
        internal static string AuthNameLbl {
            get {
                return ResourceManager.GetString("AuthNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Type.
        /// </summary>
        internal static string BusnCategoryDdl {
            get {
                return ResourceManager.GetString("BusnCategoryDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card List Tables.
        /// </summary>
        internal static string CardLbl {
            get {
                return ResourceManager.GetString("CardLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Category.
        /// </summary>
        internal static string ClientClassDdl {
            get {
                return ResourceManager.GetString("ClientClassDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        internal static string ClientTypeDdl {
            get {
                return ResourceManager.GetString("ClientTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name on Card.
        /// </summary>
        internal static string CmpyEmbNameLbl {
            get {
                return ResourceManager.GetString("CmpyEmbNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string CmpyLegalNameLbl {
            get {
                return ResourceManager.GetString("CmpyLegalNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company / Individual Name.
        /// </summary>
        internal static string CmpyNameCol {
            get {
                return ResourceManager.GetString("CmpyNameCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company / Individual Name.
        /// </summary>
        internal static string CmpyNameLbl {
            get {
                return ResourceManager.GetString("CmpyNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Registration Date.
        /// </summary>
        internal static string CmpyRegsDateDtp {
            get {
                return ResourceManager.GetString("CmpyRegsDateDtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Registration No. / Identity Card No..
        /// </summary>
        internal static string CmpyRegsNoLbl {
            get {
                return ResourceManager.GetString("CmpyRegsNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Type.
        /// </summary>
        internal static string CmpyTypeDdl {
            get {
                return ResourceManager.GetString("CmpyTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        internal static string ContactPersonLbl {
            get {
                return ResourceManager.GetString("ContactPersonLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Account Name.
        /// </summary>
        internal static string CorpCdDdl {
            get {
                return ResourceManager.GetString("CorpCdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        internal static string CreationDateCol {
            get {
                return ResourceManager.GetString("CreationDateCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        internal static string customerLbl {
            get {
                return ResourceManager.GetString("customerLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle No..
        /// </summary>
        internal static string CycNoDdl {
            get {
                return ResourceManager.GetString("CycNoDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Language.
        /// </summary>
        internal static string LangIdDdl {
            get {
                return ResourceManager.GetString("LangIdDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update Date 1.
        /// </summary>
        internal static string LastUpdDateCol {
            get {
                return ResourceManager.GetString("LastUpdDateCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchants.
        /// </summary>
        internal static string MerchantLbl {
            get {
                return ResourceManager.GetString("MerchantLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax No.
        /// </summary>
        internal static string OfficeFaxLbl {
            get {
                return ResourceManager.GetString("OfficeFaxLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No.
        /// </summary>
        internal static string OfficePhoneLbl {
            get {
                return ResourceManager.GetString("OfficePhoneLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic Type.
        /// </summary>
        internal static string PlasticTypeDdl {
            get {
                return ResourceManager.GetString("PlasticTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string PriorityCol {
            get {
                return ResourceManager.GetString("PriorityCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref Key.
        /// </summary>
        internal static string RefKeyCol {
            get {
                return ResourceManager.GetString("RefKeyCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string ReportLbl {
            get {
                return ResourceManager.GetString("ReportLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string StsCol {
            get {
                return ResourceManager.GetString("StsCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports.
        /// </summary>
        internal static string SupportLbl {
            get {
                return ResourceManager.GetString("SupportLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Description.
        /// </summary>
        internal static string TaskDespCol {
            get {
                return ResourceManager.GetString("TaskDespCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task No.
        /// </summary>
        internal static string TaskNoCol {
            get {
                return ResourceManager.GetString("TaskNoCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string WebsiteLbl {
            get {
                return ResourceManager.GetString("WebsiteLbl", resourceCulture);
            }
        }
    }
}
