//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CardtrendAccount {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CardtrendAccount() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CardtrendAccount", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No.
        /// </summary>
        internal static string AccountNoLbl {
            get {
                return ResourceManager.GetString("AccountNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Creation Date.
        /// </summary>
        internal static string ApplicationCreationLbl {
            get {
                return ResourceManager.GetString("ApplicationCreationLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Id.
        /// </summary>
        internal static string ApplicationIdLbl {
            get {
                return ResourceManager.GetString("ApplicationIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Reference.
        /// </summary>
        internal static string ApplicationReferenceLbl {
            get {
                return ResourceManager.GetString("ApplicationReferenceLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized Signatory.
        /// </summary>
        internal static string AuthorizedSignatoryLbl {
            get {
                return ResourceManager.GetString("AuthorizedSignatoryLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked Date.
        /// </summary>
        internal static string BlockedDateLbl {
            get {
                return ResourceManager.GetString("BlockedDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Category.
        /// </summary>
        internal static string BusinessCategoryDdl {
            get {
                return ResourceManager.GetString("BusinessCategoryDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Class.
        /// </summary>
        internal static string ClientClassDdl {
            get {
                return ResourceManager.GetString("ClientClassDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Type.
        /// </summary>
        internal static string ClientTypeDdl {
            get {
                return ResourceManager.GetString("ClientTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLP Point Balance.
        /// </summary>
        internal static string ClpPointBalance {
            get {
                return ResourceManager.GetString("ClpPointBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Emboss Name.
        /// </summary>
        internal static string CompanyEmbossNameLbl {
            get {
                return ResourceManager.GetString("CompanyEmbossNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string CompanyNameLbl {
            get {
                return ResourceManager.GetString("CompanyNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Registration Date.
        /// </summary>
        internal static string CompanyRegistrationDateLbl {
            get {
                return ResourceManager.GetString("CompanyRegistrationDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Registration No.
        /// </summary>
        internal static string CompanyRegistrationNoLbl {
            get {
                return ResourceManager.GetString("CompanyRegistrationNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Type.
        /// </summary>
        internal static string CompanyTypeDdl {
            get {
                return ResourceManager.GetString("CompanyTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        internal static string ContactPersonLbl {
            get {
                return ResourceManager.GetString("ContactPersonLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Code.
        /// </summary>
        internal static string CorporateCodeDdl {
            get {
                return ResourceManager.GetString("CorporateCodeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        internal static string CreationDateLbl {
            get {
                return ResourceManager.GetString("CreationDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LanguageDdl {
            get {
                return ResourceManager.GetString("LanguageDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LMS Account No.
        /// </summary>
        internal static string LmsAccountNoLbl {
            get {
                return ResourceManager.GetString("LmsAccountNoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overrides Status Tagged By User Id.
        /// </summary>
        internal static string OverridesStatusLbl {
            get {
                return ResourceManager.GetString("OverridesStatusLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Terms.
        /// </summary>
        internal static string PaymentTermsDdl {
            get {
                return ResourceManager.GetString("PaymentTermsDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic Type.
        /// </summary>
        internal static string PlasticTypeDdl {
            get {
                return ResourceManager.GetString("PlasticTypeDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string RemarksLbl {
            get {
                return ResourceManager.GetString("RemarksLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Territory.
        /// </summary>
        internal static string SalesTerritoryDdl {
            get {
                return ResourceManager.GetString("SalesTerritoryDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string StatusLbl {
            get {
                return ResourceManager.GetString("StatusLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax ID.
        /// </summary>
        internal static string TaxIdLbl {
            get {
                return ResourceManager.GetString("TaxIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Reinstatement.
        /// </summary>
        internal static string TemporaryReinstatementDdl {
            get {
                return ResourceManager.GetString("TemporaryReinstatementDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Reinstatement Date Range.
        /// </summary>
        internal static string TemporaryReinstatementLbl {
            get {
                return ResourceManager.GetString("TemporaryReinstatementLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminated Date.
        /// </summary>
        internal static string TerminatedDateLbl {
            get {
                return ResourceManager.GetString("TerminatedDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Terms.
        /// </summary>
        internal static string TradingAreaDdl {
            get {
                return ResourceManager.GetString("TradingAreaDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web User Id.
        /// </summary>
        internal static string WebUserIdLbl {
            get {
                return ResourceManager.GetString("WebUserIdLbl", resourceCulture);
            }
        }
    }
}
